root = "."
tmp_dir = "./tmp"

[build]
  cmd = """
    NODE_PATH=$(npm root -g) tailwindcss -i style/input.css -o style/output.css &&
    templ generate &&
    go build -o ./tmp/main .
  """
  full_bin = "./tmp/main"
  delay = 1000
  include_ext = ["go", "html", "templ"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_templ\\.go$"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
