services:
  webpage:
    image: 0xviva/0xviva.dev:${IMAGE_TAG:-latest}
    container_name: 0xViva.dev
    restart: unless-stopped

    environment:
      PORT: ${INTERNAL_PORT}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      CSS_VERSION: ${CSS_VERSION:-dev}

    ports:
      - "127.0.0.1:${EXTERNAL_PORT}:${INTERNAL_PORT}"
